### ISSUE TITLE
Future development version roadmap

### ISSUE THREAD

**Issue by cgmorton** [Open-ET/openet-ssebop#54]
- v0.3.0 - Add support for the LST correction

In progress in the main branch.  Code references the soil emissivity collection, so this will need to be updated/fixed for openet-core v0.1.1.
    
- v0.4.0 - Clean out old or unused code, especially in the Tcorr options

- v0.5.0 - Add full support for global calculations

**Comment by cgmorton** [comment]
Add support for using other datasets for the conversion from alfalfa to grass.  Right now this is hardcoded to NLDAS.  Not sure if this should be a separate version or maybe wrapped into the global support.

**Comment by macfriedrichs** [comment]
As of 19-Sep 2023,  phased deprecation items for consideration:

- [ ] Removing old scene-based precomputed and dynamic Tcorr calibration functions
- [ ] Removing support of Landsat Collection 1 TOA image collections (ended 2022-01-01).
- [ ] Removing associated unit tests to above items
- [ ] Other depreciated content - TBD

**Comment by cgmorton** [comment]
I started a new "v0p4_deprecation" branch.  I'm not sure the best way to flag the various parameters and methods as deprecated, but I went with the warnings module for now unless someone knows the "right" (or better) way to do this.  

The DeprecationWarning is suppressed by default for most of our use cases (jupyter notebooks, importing as a module), so I used FutureWarning for now so that the messages would show in jupyter.  I'm not sure if this is good or bad, but just a heads up that is why that is in there.

Should support for the "DYNAMIC" tcorr source be deprecated?  It seems like you are saying that above, but wanted to double check.  I kind of like the idea of keeping it since that was the original approach in so many of the papers, but it would probably require having and maintaining the tcorr climatology image collections.

Should support for computing dT dynamically using the "CIMIS", "GRIDMET", and "DAYMET" keywords be deprecated?  I set the precomputed "DAYMET_MEDIAN_V0", "DAYMET_MEDIAN_V1", and "DAYMET_MEDIAN_V2" keywords as deprecated, so it might make sense to remove all of the keywords based options and only support reading precomputed assets set with a full image collection ID.

Should support for the tmax_source keywords be deprecated?  These include CIMIS, GRIDMET, DAYMET_V3, DAYMET_V4 and a couple of MEDIAN options.  I think we should deprecate them all but want to double check.

**Comment by macfriedrichs** [comment]
The Deprecation/Future Warning seems like a reasonable approach. 

Regarding support for tcorr keywords, dT keywords, and tmax keywords - please deprecate all of those as suggested. I reviewed these options with the model PI and he is in agreement that each of those could be historically accessed/recreated using the archived (versioned) code releases.

**Comment by cgmorton** [comment]
Initial code cleanup and deprecation is being applied in v0.4.0 (#57) and further discussion of global support will be made in a separate issue (#58).
